import 'package:hive_flutter/hive_flutter.dart';
import 'package:bizniz_tracker/features/products/domain/product.dart';
import 'package:bizniz_tracker/features/sales/domain/sale.dart';

Future<void> registerHiveAdapters() async {
  await Hive.initFlutter();
  // Register adapters here. The Hive type adapter (generated by build_runner)
  // will create `ProductModelAdapter` and `SaleAdapter`. Run the code generator:
  // flutter pub run build_runner build --delete-conflicting-outputs
  if (!Hive.isAdapterRegistered(ProductModelAdapter().typeId)) {
    Hive.registerAdapter(ProductModelAdapter());
  }
  if (!Hive.isAdapterRegistered(SaleAdapter().typeId)) {
    Hive.registerAdapter(SaleAdapter());
  }
  // open boxes if you like (or open them in repositories)
  // await Hive.openBox<ProductModel>('products_box');
  // await Hive.openBox<Sale>('sales_box');
}
